### ISSUE TITLE
 Addon does not support drilldown chart

### ISSUE THREAD

**Issue by gregjopa** [ahmadsoe/ember-highcharts#76]
A highcharts drilldown chart requires additional data besides what is passed to `series`. Currently this addon's `content` parameter only passes data to `series`: https://github.com/ahmadsoe/ember-highcharts/blob/master/addon/components/high-charts.js#L34. The drilldown functionality requires an API like so:
```js
{
...
  series: seriesArray,
  drilldown: drilldownArray,
...
}
```

Ex: http://www.highcharts.com/demo/column-drilldown

I tried to implement a drilldown chart on my fork but got caught up on this issue: https://github.com/gregjopa/ember-highcharts/blob/drilldown/tests/dummy/app/components/chart-column-drilldown.js

To fix this issue we could add a check to see if the `content` argument is an array. If it's an array we assign it to `series`. If it's an object then we merge in the object as is. We could also throw an error if this `content` object is missing the `series` key. This way we could ensure backward compatibility and keep the API flexible for other highcharts modules.

What are your thoughts on how to add support for drilldown functionality?

**Comment by gregjopa** [comment]
I was wrong. You can implement a drilldown chart with this addon. You just need to include the drilldown option in the chartOptions argument (previously I was trying to include it in the `content` argument which is incorrect).

Check out PR #77 which includes a demo of how to implement a drilldown chart with this addon.

**Comment by Datamance** [comment]
Ok I think part of the problem is that I'm somehow version-locked to 0.1.3. If I try and build my project with any of the other versions, I get an error that I'm missing the highcharts dep:

[ember 05/16/16 11:13:57] version: 1.13.8
[ember 05/16/16 11:13:57] Could not find watchman, falling back to NodeWatcher for file system events.
[ember 05/16/16 11:13:57] Visit http://www.ember-cli.com/user-guide/#watchman for more info.
[ember 05/16/16 11:13:57] BuildingBuilding...
[ember 05/16/16 11:14:01] Cannot find module 'highcharts'
[ember 05/16/16 11:14:01] Error: Cannot find module 'highcharts'

I get the sneaking suspicion that 0.3.0+ has what I need in order to get drilldown to work.

**Comment by gregjopa** [comment]
A few versions ago we switched from bower to npm for managing the highcharts dependency with this addon. Make sure you have the following in your package.json dependencies:

```json
"devDependencies": {
  "ember-highcharts": "0.4.3",
  "highcharts": "4.2.5"
}
```

**Comment by Datamance** [comment]
@gregjopa thank you so much for following up!

Can you confirm or deny that I need to upgrade past 0.1.3 to use drilldown functionality? Just want to make sure I'm not wasting too much time :)

**Comment by gregjopa** [comment]
Yes, I'd recommend upgrading to the most recent version. The config options for this addon have changed since 0.1.3:

https://github.com/ahmadsoe/ember-highcharts/blob/v0.1.3/index.js vs
https://github.com/ahmadsoe/ember-highcharts/blob/master/index.js
