### ISSUE TITLE
Might be a bug (using dynamic data in highmaps)

### ISSUE THREAD

**Issue by arthur-zheng** [ahmadsoe/ember-highcharts#83]
Hey highchart ninjas,
Thanks again for help me last time!

This time, I might found a bug:

For highmaps, if you only put series to highchart component (as how you use highchart) using `content=<your content>`, it doesn't work. It only works if you put it inside `chartConfig` (as how you use a pure js highchart) for the init one-time render.

However another problem comes when data is dynamic, reason is the changing of `chartConfig` file doesn't trigger highmap's re-render, Thus you have to also put the content into `content=<your content>`.

Conclusion: by putting chart data in both places (`content` and `chartConfig`), your dynamic map will fully works.

I suspect this is a bug. Any ideas?
Thanks!

**Comment by gregjopa** [comment]
There is a Highmaps example in the tests/dummy app here: https://github.com/ahmadsoe/ember-highcharts/blob/master/tests/dummy/app/components/chart-basic-map.js. The series data is only put in the `content` param in this example and it works fine.

Is there a specific Highmaps demo that you are trying to implement? I need to see your code in order to help troubleshoot.

**Comment by gregjopa** [comment]
Closing this. Please reopen if you are still having issues.
